---
# Source: techradar-data/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: techradar-data
  labels:
    app.kubernetes.io/instance: techradar-data
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-data
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: techradar-data-0.1.0
  namespace: ra-production-techradar
data:
  init-data.sh: |
    #!/bin/bash
    set -e;
    if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER "${POSTGRES_NON_ROOT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO "${POSTGRES_NON_ROOT_USER}";
        ALTER DATABASE ${POSTGRES_DB} OWNER TO "${POSTGRES_NON_ROOT_USER}";
    EOSQL
    else
      echo "SETUP INFO: No Environment variables given!"
    fi
---
# Source: techradar-data/templates/common.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: techradar-data
  labels:
    app.kubernetes.io/instance: techradar-data
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-data
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: techradar-data-0.1.0
  namespace: ra-production-techradar
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "300Gi"
  storageClassName: "nfs-client"
---
# Source: techradar-data/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: techradar-data-postgres
  labels:
    app.kubernetes.io/instance: techradar-data
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-data
    app.kubernetes.io/service: techradar-data-postgres
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: techradar-data-0.1.0
  namespace: ra-production-techradar
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/controller: postgres
    app.kubernetes.io/instance: techradar-data
    app.kubernetes.io/name: techradar-data
---
# Source: techradar-data/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techradar-data-postgres
  labels:
    app.kubernetes.io/controller: postgres
    app.kubernetes.io/instance: techradar-data
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-data
    app.kubernetes.io/version: 1.0.9
    helm.sh/chart: techradar-data-0.1.0
  namespace: ra-production-techradar
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: postgres
      app.kubernetes.io/name: techradar-data
      app.kubernetes.io/instance: techradar-data
  template:
    metadata:
      annotations: 
        checksum/configMaps: 7859849155807302ee841322250b12721fd5c247925f801ef52dfce4cdc4a681
      labels: 
        app.kubernetes.io/controller: postgres
        app.kubernetes.io/instance: techradar-data
        app.kubernetes.io/name: techradar-data
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - env:
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_HOST
            value: postgres-service
          - name: POSTGRES_DB
            value: techradar
          envFrom:
          - secretRef:
              name: postgres-secrets
          image: postgres:17
          imagePullPolicy: IfNotPresent
          name: main
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
          - mountPath: /docker-entrypoint-initdb.d/init-techradar-user.sh
            name: postgres-init-data
            subPath: init-data.sh
          - mountPath: /postgres-secrets
            name: postgres-secrets
      volumes: 
        - name: postgres-data
          persistentVolumeClaim:
            claimName: techradar-data
        - configMap:
            name: techradar-data
          name: postgres-init-data
        - name: postgres-secrets
          secret:
            secretName: postgres-secrets
