---
# Source: identity-server-admin-api/templates/common.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-server-admin-api
  labels:
    app.kubernetes.io/instance: identity-server-admin-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-server-admin-api
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: identity-server-admin-api-0.1.0
  namespace: platform-production
data:
  IdentityServer__Authority: https://auth.mattgerega.com
  Serilog__MinimumLevel__Default: Warning
  Telemetry__ActivitySourceName: Identity.Admin.Api.Production.Activity
  Telemetry__Log__Otlp__Endpoint: http://production-grafana-alloy.grafana:4317
  Telemetry__MeterName: Identity.Admin.Api.Production.Meter
  Telemetry__Metrics__Otlp__Endpoint: http://production-grafana-alloy.grafana:4317
  Telemetry__ServiceName: Identity.Admin.Api.Production
  Telemetry__Trace__Otlp__Endpoint: http://production-grafana-alloy.grafana:4317
---
# Source: identity-server-admin-api/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: identity-server-admin-api
  labels:
    app.kubernetes.io/instance: identity-server-admin-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-server-admin-api
    app.kubernetes.io/service: identity-server-admin-api
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: identity-server-admin-api-0.1.0
  namespace: platform-production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: identity-server-admin-api
    app.kubernetes.io/name: identity-server-admin-api
---
# Source: identity-server-admin-api/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server-admin-api
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: identity-server-admin-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: identity-server-admin-api
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: identity-server-admin-api-0.1.0
  namespace: platform-production
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: identity-server-admin-api
      app.kubernetes.io/instance: identity-server-admin-api
  template:
    metadata:
      annotations: 
        checksum/configMaps: 93c36b4152c6c592adf0747d7f2fb9cee23379ed50f9ec70a8cd848539763474
      labels: 
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: identity-server-admin-api
        app.kubernetes.io/name: identity-server-admin-api
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - configMapRef:
              name: identity-server-admin-api
          - secretRef:
              name: identity-server-admin-api-secrets
          image: ghcr.io/spyder007/identity_admin_api:3.1.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
