---
# Source: web/templates/common.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-common
  labels:
    app.kubernetes.io/instance: web
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: web
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: web-0.1.0
  namespace: pitstop-production
data:
  Logging__LogLevel__Default: Warning
  Telemetry__Log__Otlp__Endpoint: http://production-grafana-alloy.grafana.svc.cluster.local:4317
  Telemetry__Metrics__Otlp__Endpoint: http://production-grafana-alloy.grafana.svc.cluster.local:4317
  Telemetry__Trace__Otlp__Endpoint: http://production-grafana-alloy.grafana.svc.cluster.local:4317
---
# Source: web/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  labels:
    app.kubernetes.io/instance: web
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: web
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: web-0.1.0
  namespace: pitstop-production
data:
  Telemetry__ActivitySourceName: PitStop.Web.Activity
  Telemetry__MeterName: PitStop.Web.Meter
  Telemetry__ServiceName: PitStop.Web
---
# Source: web/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/instance: web
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: web
    app.kubernetes.io/service: web
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: web-0.1.0
  namespace: pitstop-production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/name: web
---
# Source: web/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app.kubernetes.io/controller: web
    app.kubernetes.io/instance: web
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: web
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: web-0.1.0
  namespace: pitstop-production
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: web
      app.kubernetes.io/name: web
      app.kubernetes.io/instance: web
  template:
    metadata:
      annotations: 
        checksum/configMaps: e40c710d1ef21ad4dae7c2244a5953f63972d6463e528b364ccc7691edd386ee
      labels: 
        app.kubernetes.io/controller: web
        app.kubernetes.io/instance: web
        app.kubernetes.io/name: web
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - secretRef:
              name: web-secrets
          - configMapRef:
              name: web-common
          - configMapRef:
              name: web
          image: ghcr.io/spydersoft-consulting/pitstop-web:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
---
# Source: web/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web
  labels:
    app.kubernetes.io/instance: web
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: web
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: web-0.1.0
  namespace: pitstop-production
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "pitstop.mattgerega.com"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: web
        namespace: pitstop-production
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
