---
# Source: pitstop-data/templates/data-api-es.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-api-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: data-api-secrets
    template:
      type: kubernetes.io/secret
      engineVersion: v2
      data:
        ConnectionStrings__pitstop-db: "Host=pitstop-data-postgres;Database=pitstop;Username={{ .db_user }};Password={{ .db_password }}"
        FileStore__ClientId: "{{ .filestore_clientid }}"
        FileStore__ClientSecret: "{{ .filestore_clientsecret }}"
  data:
  - secretKey: db_user
    remoteRef:
      key: secrets-k8/pitstop/production/postgres
      property: user
  - secretKey: db_password
    remoteRef:
      key: secrets-k8/pitstop/production/postgres
      property: password
  - secretKey: filestore_clientid
    remoteRef:
      key: secrets-k8/pitstop/production/filestore
      property: clientid
  - secretKey: filestore_clientsecret
    remoteRef:
      key: secrets-k8/pitstop/production/filestore
      property: clientsecret
