---
# Source: pitstop-data/templates/data-api-es.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-api-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: data-api-secrets
    template:
      type: kubernetes.io/secret
      engineVersion: v2
      data:
        ConnectionStrings__pitstop-db: "Host=pitstop-data-postgres;Database=pitstop;Username={{ .db_user }};Password={{ .db_password }}"
  data:
  - secretKey: db_user
    remoteRef:
      key: secrets-k8/pitstop/production/postgres
      property: user
  - secretKey: db_password
    remoteRef:
      key: secrets-k8/pitstop/production/postgres
      property: password
