dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 5.0.1
apiVersion: v2
type: application
version: 5.0.1
appVersion: 3.0.2-18
description: Node Red Helm Chart
name: nodered-home


