persistence:
  data:
    size: 2Gi
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    enabled: true
    storageClass: nfs-client
service:
  main:
    primary: true
    ports:
      http:
        primary: true
        port: 1880
        enabled: true
    type: ClusterIP
    controller: main
route:
  main:
    rules:
    - backendRefs:
      - identifier: main
        weight: 1
        port: 1880
        group: ""
        kind: Service
      matches:
      - path:
          value: /
          type: PathPrefix
    hostnames:
    - nodered.mattgerega.net
    kind: HTTPRoute
    enabled: true
    parentRefs:
    - kind: Gateway
      name: main
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
controllers:
  main:
    replicas: 1
    enabled: true
    type: deployment
    containers:
      main:
        image:
          tag: 5.0.8
          repository: nodered/node-red
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 5m
        probes:
          liveness:
            type: TCP
            custom: false
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 10
              failureThreshold: 3
            enabled: true
          readiness:
            type: TCP
            custom: false
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 10
              failureThreshold: 3
            enabled: true
          startup:
            type: TCP
            custom: false
            spec:
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 5
              failureThreshold: 30
            enabled: true
        env:
          FLOWS: flows.json
          TZ: America/New_York
          NODE_RED_ENABLE_SAFE_MODE: 
          NODE_OPTIONS: 
          NODE_RED_ENABLE_PROJECTS: 
        strategy:
          type: Recreate
    revisionHistoryLimit: 3
    strategy: Recreate

