route:
  main:
    rules:
    - backendRefs:
      - group: ""
        identifier: main
        port: 1880
        kind: Service
        weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /
    hostnames:
    - nodered.mattgerega.net
    enabled: true
    parentRefs:
    - group: gateway.networking.k8s.io
      namespace: envoy-gateway-system
      name: main
      kind: Gateway
    kind: HTTPRoute
controllers:
  main:
    strategy: Recreate
    enabled: true
    containers:
      main:
        image:
          pullPolicy: IfNotPresent
          tag: 4.1.8
          repository: nodered/node-red
        env:
          TZ: America/New_York
          NODE_RED_ENABLE_PROJECTS: 
          NODE_RED_ENABLE_SAFE_MODE: 
          FLOWS: flows.json
          NODE_OPTIONS: 
        strategy:
          type: Recreate
        probes:
          readiness:
            type: TCP
            enabled: true
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              initialDelaySeconds: 0
              failureThreshold: 3
            custom: false
          startup:
            type: TCP
            enabled: true
            spec:
              periodSeconds: 5
              timeoutSeconds: 1
              initialDelaySeconds: 0
              failureThreshold: 30
            custom: false
          liveness:
            type: TCP
            enabled: true
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              initialDelaySeconds: 0
              failureThreshold: 3
            custom: false
    revisionHistoryLimit: 3
    type: deployment
    replicas: 1
service:
  main:
    type: ClusterIP
    controller: main
    ports:
      http:
        enabled: true
        port: 1880
        primary: true
    primary: true
persistence:
  data:
    size: 2Gi
    storageClass: nfs-client
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteMany

