controllers:
  main:
    containers:
      main:
        strategy:
          type: Recreate
        env:
          NODE_RED_ENABLE_PROJECTS: 
          NODE_OPTIONS: 
          TZ: America/New_York
          FLOWS: flows.json
          NODE_RED_ENABLE_SAFE_MODE: 
        image:
          pullPolicy: IfNotPresent
          tag: 4.1.11
          repository: nodered/node-red
        probes:
          readiness:
            type: TCP
            enabled: true
            custom: false
            spec:
              periodSeconds: 10
              failureThreshold: 3
              initialDelaySeconds: 0
              timeoutSeconds: 1
          liveness:
            type: TCP
            enabled: true
            custom: false
            spec:
              periodSeconds: 10
              failureThreshold: 3
              initialDelaySeconds: 0
              timeoutSeconds: 1
          startup:
            type: TCP
            enabled: true
            custom: false
            spec:
              periodSeconds: 5
              failureThreshold: 30
              initialDelaySeconds: 0
              timeoutSeconds: 1
    type: deployment
    strategy: Recreate
    enabled: true
    revisionHistoryLimit: 3
    replicas: 1
service:
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 1880
        enabled: true
        primary: true
    primary: true
route:
  main:
    hostnames:
    - nodered.mattgerega.net
    parentRefs:
    - name: main
      group: gateway.networking.k8s.io
      namespace: envoy-gateway-system
      kind: Gateway
    enabled: true
    kind: HTTPRoute
    rules:
    - backendRefs:
      - weight: 1
        port: 1880
        group: ""
        identifier: main
        kind: Service
      matches:
      - path:
          value: /
          type: PathPrefix
persistence:
  data:
    type: persistentVolumeClaim
    storageClass: nfs-client
    accessMode: ReadWriteMany
    size: 2Gi
    enabled: true

