---
# Source: unifi-ipmanager/templates/common.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ipmanager-app-ipmanager
  labels:
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager-app
    app.kubernetes.io/version: 1.1.1-beta.136
    helm.sh/chart: unifi-ipmanager-1.1.1-beta.136
  namespace: production
data:
  Identity__ApiName: unifi.ipmanager
  UnifiControllerOptions__DnsZone: gerega.net
  UnifiControllerOptions__Url: https://unifi.gerega.net
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ipmanager-app-config-js
  labels:
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager-app
    app.kubernetes.io/version: 1.1.1-beta.136
    helm.sh/chart: unifi-ipmanager-1.1.1-beta.136
  namespace: production
data:
  config.js: |
    window.unifi_client_api = {
      backend: 'https://api.mattgerega.com/unifi/ipmanager',
    };
  
    window.unifi_client_auth = {
      authority: 'https://auth.mattgerega.com/',
      clientId: 'unifiwebclient',
      redirectUri: 'https://uni.mattgerega.com',
    };
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: unifi-ipmanager-app-api
  labels:
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager-app
    app.kubernetes.io/service: unifi-ipmanager-app-api
    app.kubernetes.io/version: 1.1.1-beta.136
    helm.sh/chart: unifi-ipmanager-1.1.1-beta.136
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: api
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/name: unifi-ipmanager-app
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: unifi-ipmanager-app-frontend
  labels:
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager-app
    app.kubernetes.io/service: unifi-ipmanager-app-frontend
    app.kubernetes.io/version: 1.1.1-beta.136
    helm.sh/chart: unifi-ipmanager-1.1.1-beta.136
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: frontend
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/name: unifi-ipmanager-app
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-ipmanager-app-api
  labels:
    app.kubernetes.io/controller: api
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager-app
    app.kubernetes.io/version: 1.1.1-beta.136
    helm.sh/chart: unifi-ipmanager-1.1.1-beta.136
  namespace: production
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: api
      app.kubernetes.io/name: unifi-ipmanager-app
      app.kubernetes.io/instance: unifi-ipmanager-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: 0dcea50de498bcb435018f38edbcc960edfe93d1b29225aaa7a0fdef4826d74b
      labels: 
        app.kubernetes.io/controller: api
        app.kubernetes.io/instance: unifi-ipmanager-app
        app.kubernetes.io/name: unifi-ipmanager-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - configMapRef:
              name: home-automation-common-config
          - configMapRef:
              name: unifi-ipmanager-app-ipmanager
          - secretRef:
              name: unifi-secrets
          image: ghcr.io/spyder007/unifi-ipmanager:1.1.1-beta.136
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /usr/share/nginx/html/config.js
            name: config-js
            subPath: config.js
      volumes: 
        - configMap:
            name: unifi-ipmanager-app-config-js
          name: config-js
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-ipmanager-app-frontend
  labels:
    app.kubernetes.io/controller: frontend
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager-app
    app.kubernetes.io/version: 1.1.1-beta.136
    helm.sh/chart: unifi-ipmanager-1.1.1-beta.136
  namespace: production
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: frontend
      app.kubernetes.io/name: unifi-ipmanager-app
      app.kubernetes.io/instance: unifi-ipmanager-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: 0dcea50de498bcb435018f38edbcc960edfe93d1b29225aaa7a0fdef4826d74b
      labels: 
        app.kubernetes.io/controller: frontend
        app.kubernetes.io/instance: unifi-ipmanager-app
        app.kubernetes.io/name: unifi-ipmanager-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - image: ghcr.io/spyder007/unifi-client:1.1.1-beta.136
          imagePullPolicy: IfNotPresent
          name: main
          volumeMounts:
          - mountPath: /usr/share/nginx/html/config.js
            name: config-js
            subPath: config.js
      volumes: 
        - configMap:
            name: unifi-ipmanager-app-config-js
          name: config-js
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi-ipmanager-app-api
  labels:
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager-app
    app.kubernetes.io/version: 1.1.1-beta.136
    helm.sh/chart: unifi-ipmanager-1.1.1-beta.136
  namespace: production
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "api.mattgerega.com"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: unifi-ipmanager-app-api
        namespace: production
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /unifi/ipmanager
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /
              type: ReplacePrefixMatch
---
# Source: unifi-ipmanager/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi-ipmanager-app-frontend
  labels:
    app.kubernetes.io/instance: unifi-ipmanager-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unifi-ipmanager-app
    app.kubernetes.io/version: 1.1.1-beta.136
    helm.sh/chart: unifi-ipmanager-1.1.1-beta.136
  namespace: production
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "uni.mattgerega.com"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: unifi-ipmanager-app-frontend
        namespace: production
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
