---
# Source: rabbitmq/templates/rabbitmq-secrets-es.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rabbitmq-secrets
  data:
  - secretKey: RABBITMQ_DEFAULT_USER
    remoteRef:
      key: secrets-k8/audit/production/rabbitmq
      property: user
  - secretKey: RABBITMQ_DEFAULT_PASS
    remoteRef:
      key: secrets-k8/audit/production/rabbitmq
      property: password
