appVersion: 3.0.2-18
description: n8n Helm Chart
type: application
version: 5.0.1
apiVersion: v2
dependencies:
- name: common
  version: 5.0.1
  repository: https://bjw-s-labs.github.io/helm-charts
name: n8n


