version: 5.0.1
description: n8n Helm Chart
apiVersion: v2
dependencies:
- repository: https://bjw-s-labs.github.io/helm-charts
  name: common
  version: 5.0.1
name: n8n
type: application
appVersion: 3.0.2-18


