route:
  main:
    kind: HTTPRoute
    enabled: true
    parentRefs:
    - kind: Gateway
      name: main
      group: gateway.networking.k8s.io
      namespace: envoy-gateway-system
    rules:
    - backendRefs:
      - kind: Service
        port: 5678
        weight: 1
        group: ""
        identifier: main
      matches:
      - path:
          type: PathPrefix
          value: /
    hostnames:
    - n8n.mattgerega.com
persistence:
  postgres-secrets:
    type: secret
    name: postgres-secrets
    enabled: true
  data:
    accessMode: ReadWriteMany
    enabled: true
    advancedMounts:
      main:
        volume-permissions:
        - path: /home/node/.n8n
        main:
        - path: /home/node/.n8n
    size: 2Gi
    storageClass: nfs-client
    type: persistentVolumeClaim
  postgres-data:
    accessMode: ReadWriteMany
    enabled: true
    advancedMounts:
      postgres:
        main:
        - path: /var/lib/postgresql/data
    size: 300Gi
    storageClass: nfs-client
    type: persistentVolumeClaim
  postgres-init-data:
    type: configMap
    identifier: postgres-init-data
    enabled: true
    advancedMounts:
      postgres:
        main:
        - subPath: init-data.sh
          path: /docker-entrypoint-initdb.d/init-n8n-user.sh
controllers:
  postgres:
    type: deployment
    enabled: true
    revisionHistoryLimit: 3
    strategy: Recreate
    replicas: 1
    containers:
      main:
        envFrom:
        - secretRef:
            name: postgres-secrets
        strategy:
          type: Recreate
        image:
          tag: 17
          repository: postgres
          pullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PORT
          value: 5432
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_DB
          value: n8n
  main:
    type: deployment
    enabled: true
    revisionHistoryLimit: 3
    initContainers:
      volume-permissions:
        volumeMounts:
        - mountPath: /home/node/.n8n
          name: '{{ .Release.Name }}-data'
        image:
          tag: 1.36
          repository: busybox
        command:
        - sh
        - -c
        - chown 1000:1000 /home/node/.n8n
    strategy: Recreate
    replicas: 1
    containers:
      main:
        probes:
          liveness:
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              failureThreshold: 3
              timeoutSeconds: 1
            type: TCP
            custom: false
            enabled: true
          startup:
            spec:
              initialDelaySeconds: 0
              periodSeconds: 5
              failureThreshold: 30
              timeoutSeconds: 1
            type: TCP
            custom: false
            enabled: true
          readiness:
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              failureThreshold: 3
              timeoutSeconds: 1
            type: TCP
            custom: false
            enabled: true
        env:
        - name: DB_TYPE
          value: postgresdb
        - name: DB_POSTGRESDB_HOST
          value: '{{ .Release.Name }}-postgres'
        - name: DB_POSTGRESDB_PORT
          value: 5432
        - name: DB_POSTGRESDB_DATABASE
          value: n8n
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_NON_ROOT_USER
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_NON_ROOT_PASSWORD
        image:
          tag: 2.22.5
          repository: n8nio/n8n
          pullPolicy: IfNotPresent
        strategy:
          type: Recreate
        envFrom:
        - configMapRef:
            name: '{{ .Release.Name }}'
configMaps:
  n8n:
    data:
      N8N_PROTOCOL: http
      N8N_RUNNERS_ENABLED: "true"
      N8N_PORT: "5678"
    enabled: true
  postgres-init-data:
    data:
      init-data.sh: |
        #!/bin/bash
        set -e;
        if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
          psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE USER "${POSTGRES_NON_ROOT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
            GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO "${POSTGRES_NON_ROOT_USER}";
        EOSQL
        else
          echo "SETUP INFO: No Environment variables given!"
        fi
    enabled: true
service:
  postgres:
    ports:
      postgres:
        port: 5432
        enabled: true
    type: ClusterIP
    primary: false
    controller: postgres
  main:
    ports:
      http:
        port: 5678
        primary: true
        enabled: true
    type: ClusterIP
    primary: true
    controller: main

