configMaps:
  n8n:
    enabled: true
    data:
      N8N_PORT: "5678"
      N8N_RUNNERS_ENABLED: "true"
      N8N_PROTOCOL: http
  postgres-init-data:
    enabled: true
    data:
      init-data.sh: |
        #!/bin/bash
        set -e;
        if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
          psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE USER "${POSTGRES_NON_ROOT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
            GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO "${POSTGRES_NON_ROOT_USER}";
        EOSQL
        else
          echo "SETUP INFO: No Environment variables given!"
        fi
service:
  main:
    primary: true
    controller: main
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 5678
  postgres:
    primary: false
    controller: postgres
    type: ClusterIP
    ports:
      postgres:
        enabled: true
        port: 5432
controllers:
  main:
    enabled: true
    type: deployment
    revisionHistoryLimit: 3
    initContainers:
      volume-permissions:
        command:
        - sh
        - -c
        - chown 1000:1000 /home/node/.n8n
        volumeMounts:
        - name: '{{ .Release.Name }}-data'
          mountPath: /home/node/.n8n
        image:
          tag: 1.36
          repository: busybox
    containers:
      main:
        env:
        - name: DB_TYPE
          value: postgresdb
        - name: DB_POSTGRESDB_HOST
          value: '{{ .Release.Name }}-postgres'
        - name: DB_POSTGRESDB_PORT
          value: 5432
        - name: DB_POSTGRESDB_DATABASE
          value: n8n
        - valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_NON_ROOT_USER
          name: DB_POSTGRESDB_USER
        - valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_NON_ROOT_PASSWORD
          name: DB_POSTGRESDB_PASSWORD
        envFrom:
        - configMapRef:
            name: '{{ .Release.Name }}'
        strategy:
          type: Recreate
        probes:
          readiness:
            custom: false
            type: TCP
            enabled: true
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              failureThreshold: 3
              timeoutSeconds: 1
          liveness:
            custom: false
            type: TCP
            enabled: true
            spec:
              initialDelaySeconds: 0
              periodSeconds: 10
              failureThreshold: 3
              timeoutSeconds: 1
          startup:
            custom: false
            type: TCP
            enabled: true
            spec:
              initialDelaySeconds: 0
              periodSeconds: 5
              failureThreshold: 30
              timeoutSeconds: 1
        image:
          pullPolicy: IfNotPresent
          repository: n8nio/n8n
          tag: 2.21.4
    strategy: Recreate
    replicas: 1
  postgres:
    enabled: true
    type: deployment
    revisionHistoryLimit: 3
    containers:
      main:
        image:
          pullPolicy: IfNotPresent
          repository: postgres
          tag: 17
        env:
        - name: POSTGRES_PORT
          value: 5432
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_DB
          value: n8n
        envFrom:
        - secretRef:
            name: postgres-secrets
        strategy:
          type: Recreate
    strategy: Recreate
    replicas: 1
persistence:
  postgres-secrets:
    name: postgres-secrets
    type: secret
    enabled: true
  postgres-data:
    enabled: true
    storageClass: nfs-client
    size: 300Gi
    type: persistentVolumeClaim
    advancedMounts:
      postgres:
        main:
        - path: /var/lib/postgresql/data
    accessMode: ReadWriteMany
  data:
    enabled: true
    storageClass: nfs-client
    size: 2Gi
    type: persistentVolumeClaim
    advancedMounts:
      main:
        main:
        - path: /home/node/.n8n
        volume-permissions:
        - path: /home/node/.n8n
    accessMode: ReadWriteMany
  postgres-init-data:
    advancedMounts:
      postgres:
        main:
        - subPath: init-data.sh
          path: /docker-entrypoint-initdb.d/init-n8n-user.sh
    type: configMap
    enabled: true
    identifier: postgres-init-data
route:
  main:
    enabled: true
    rules:
    - matches:
      - path:
          value: /
          type: PathPrefix
      backendRefs:
      - identifier: main
        group: ""
        port: 5678
        kind: Service
        weight: 1
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
    kind: HTTPRoute
    hostnames:
    - n8n.mattgerega.com

