route:
  main:
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway-system
      name: main
    enabled: true
    kind: HTTPRoute
    rules:
    - matches:
      - path:
          value: /
          type: PathPrefix
      backendRefs:
      - group: ""
        port: 5678
        kind: Service
        weight: 1
        identifier: main
    hostnames:
    - n8n.mattgerega.com
controllers:
  main:
    containers:
      main:
        image:
          repository: n8nio/n8n
          tag: 2.26.4
          pullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: '{{ .Release.Name }}'
        strategy:
          type: Recreate
        probes:
          liveness:
            custom: false
            spec:
              failureThreshold: 3
              timeoutSeconds: 1
              periodSeconds: 10
              initialDelaySeconds: 0
            enabled: true
            type: TCP
          startup:
            custom: false
            spec:
              failureThreshold: 30
              timeoutSeconds: 1
              periodSeconds: 5
              initialDelaySeconds: 0
            enabled: true
            type: TCP
          readiness:
            custom: false
            spec:
              failureThreshold: 3
              timeoutSeconds: 1
              periodSeconds: 10
              initialDelaySeconds: 0
            enabled: true
            type: TCP
        env:
        - value: postgresdb
          name: DB_TYPE
        - value: '{{ .Release.Name }}-postgres'
          name: DB_POSTGRESDB_HOST
        - value: 5432
          name: DB_POSTGRESDB_PORT
        - value: n8n
          name: DB_POSTGRESDB_DATABASE
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_NON_ROOT_USER
              name: postgres-secrets
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_NON_ROOT_PASSWORD
              name: postgres-secrets
    replicas: 1
    revisionHistoryLimit: 3
    initContainers:
      volume-permissions:
        command:
        - sh
        - -c
        - chown 1000:1000 /home/node/.n8n
        image:
          repository: busybox
          tag: 1.36
        volumeMounts:
        - name: '{{ .Release.Name }}-data'
          mountPath: /home/node/.n8n
    type: deployment
    strategy: Recreate
    enabled: true
  postgres:
    containers:
      main:
        envFrom:
        - secretRef:
            name: postgres-secrets
        env:
        - value: 5432
          name: POSTGRES_PORT
        - value: postgres-service
          name: POSTGRES_HOST
        - value: n8n
          name: POSTGRES_DB
        strategy:
          type: Recreate
        image:
          repository: postgres
          tag: 17
          pullPolicy: IfNotPresent
    replicas: 1
    revisionHistoryLimit: 3
    type: deployment
    strategy: Recreate
    enabled: true
service:
  main:
    controller: main
    primary: true
    ports:
      http:
        primary: true
        port: 5678
        enabled: true
    type: ClusterIP
  postgres:
    controller: postgres
    primary: false
    ports:
      postgres:
        port: 5432
        enabled: true
    type: ClusterIP
persistence:
  data:
    storageClass: nfs-client
    advancedMounts:
      main:
        main:
        - path: /home/node/.n8n
        volume-permissions:
        - path: /home/node/.n8n
    accessMode: ReadWriteMany
    type: persistentVolumeClaim
    enabled: true
    size: 2Gi
  postgres-data:
    storageClass: nfs-client
    advancedMounts:
      postgres:
        main:
        - path: /var/lib/postgresql/data
    accessMode: ReadWriteMany
    type: persistentVolumeClaim
    enabled: true
    size: 300Gi
  postgres-secrets:
    enabled: true
    name: postgres-secrets
    type: secret
  postgres-init-data:
    identifier: postgres-init-data
    enabled: true
    advancedMounts:
      postgres:
        main:
        - path: /docker-entrypoint-initdb.d/init-n8n-user.sh
          subPath: init-data.sh
    type: configMap
configMaps:
  n8n:
    data:
      N8N_PORT: "5678"
      N8N_PROTOCOL: http
      N8N_RUNNERS_ENABLED: "true"
    enabled: true
  postgres-init-data:
    data:
      init-data.sh: |
        #!/bin/bash
        set -e;
        if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
          psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE USER "${POSTGRES_NON_ROOT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
            GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO "${POSTGRES_NON_ROOT_USER}";
        EOSQL
        else
          echo "SETUP INFO: No Environment variables given!"
        fi
    enabled: true

