---
# Source: techradar/templates/common.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: techradar-app-data-api
  labels:
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-app
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: techradar-2.1.0
  namespace: ra-production-techradar
data:
  Telemetry__ActivitySourceName: TechRadar.Data.Activity
  Telemetry__MeterName: TechRadar.Data.Meter
  Telemetry__ServiceName: TechRadar.Data
---
# Source: techradar/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: techradar-app-frontend
  labels:
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-app
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: techradar-2.1.0
  namespace: ra-production-techradar
data:
  Telemetry__ActivitySourceName: TechRadar.Frontend.Activity
  Telemetry__MeterName: TechRadar.Frontend.Meter
  Telemetry__ServiceName: TechRadar.Frontend
---
# Source: techradar/templates/common.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: techradar-app-common
  labels:
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-app
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: techradar-2.1.0
  namespace: ra-production-techradar
data:
  Telemetry__Log__Otlp__Endpoint: http://production-grafana-alloy.grafana.svc.cluster.local:4318
  Telemetry__Log__Otlp__Headers__X-Scope-OrgID: production
  Telemetry__Metrics__Otlp__Endpoint: http://production-grafana-alloy.grafana.svc.cluster.local:4318
  Telemetry__Metrics__Otlp__Headers__X-Scope-OrgID: production
  Telemetry__Trace__Otlp__Endpoint: http://production-grafana-alloy.grafana.svc.cluster.local:4318
  Telemetry__Trace__Otlp__Headers__X-Scope-OrgID: production
---
# Source: techradar/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: techradar-app-data-api
  labels:
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-app
    app.kubernetes.io/service: techradar-app-data-api
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: techradar-2.1.0
  namespace: ra-production-techradar
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: data-api
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/name: techradar-app
---
# Source: techradar/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: techradar-app-frontend
  labels:
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-app
    app.kubernetes.io/service: techradar-app-frontend
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: techradar-2.1.0
  namespace: ra-production-techradar
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: frontend
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/name: techradar-app
---
# Source: techradar/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techradar-app-frontend
  labels:
    app.kubernetes.io/controller: frontend
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-app
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: techradar-2.1.0
  namespace: ra-production-techradar
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: frontend
      app.kubernetes.io/name: techradar-app
      app.kubernetes.io/instance: techradar-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: d335f60ed685e8037fc83d5603d5ea721a39a97ea2ee0f97f5bf619497d16bf1
      labels: 
        app.kubernetes.io/controller: frontend
        app.kubernetes.io/instance: techradar-app
        app.kubernetes.io/name: techradar-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - secretRef:
              name: techradar-frontend
          - configMapRef:
              name: techradar-app-common
          - configMapRef:
              name: techradar-app-frontend
          image: ghcr.io/spydersoft-consulting/techradar-frontend:2.1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
---
# Source: techradar/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techradar-app-data-api
  labels:
    app.kubernetes.io/controller: data-api
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-app
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: techradar-2.1.0
  namespace: ra-production-techradar
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: data-api
      app.kubernetes.io/name: techradar-app
      app.kubernetes.io/instance: techradar-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: d335f60ed685e8037fc83d5603d5ea721a39a97ea2ee0f97f5bf619497d16bf1
      labels: 
        app.kubernetes.io/controller: data-api
        app.kubernetes.io/instance: techradar-app
        app.kubernetes.io/name: techradar-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - secretRef:
              name: techradar-data-api
          - configMapRef:
              name: techradar-app-common
          - configMapRef:
              name: techradar-app-data-api
          image: ghcr.io/spydersoft-consulting/techradar-data-api:2.1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
---
# Source: techradar/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: techradar-app
  labels:
    app.kubernetes.io/instance: techradar-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: techradar-app
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: techradar-2.1.0
  namespace: ra-production-techradar
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "techradar.mattgerega.com"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: techradar-app-frontend
        namespace: ra-production-techradar
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
