---
# Source: filestore-api/templates/common.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filestore-app
  labels:
    app.kubernetes.io/instance: filestore-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: filestore-app
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: filestore-api-1.0.0
  namespace: platform-production
data:
  Auth__Audience: filestore-api
  Auth__Authority: https://auth.mattgerega.com
  Serilog__MinimumLevel__Default: Warning
  Storage__BucketName: filestore
  Storage__Region: us-east-1
  Storage__ServiceUrl: https://gs3.mattgerega.net
  Telemetry__ActivitySourceName: FileStore.Production.Activity
  Telemetry__Log__Otlp__Endpoint: http://production-grafana-alloy.grafana:4317
  Telemetry__MeterName: FileStore.Production.Meter
  Telemetry__Metrics__Otlp__Endpoint: http://production-grafana-alloy.grafana:4317
  Telemetry__ServiceName: FileStore.Production
  Telemetry__Trace__Otlp__Endpoint: http://production-grafana-alloy.grafana:4317
---
# Source: filestore-api/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: filestore-app
  labels:
    app.kubernetes.io/instance: filestore-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: filestore-app
    app.kubernetes.io/service: filestore-app
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: filestore-api-1.0.0
  namespace: platform-production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: filestore-api
    app.kubernetes.io/instance: filestore-app
    app.kubernetes.io/name: filestore-app
---
# Source: filestore-api/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestore-app
  labels:
    app.kubernetes.io/controller: filestore-api
    app.kubernetes.io/instance: filestore-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: filestore-app
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: filestore-api-1.0.0
  namespace: platform-production
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: filestore-api
      app.kubernetes.io/name: filestore-app
      app.kubernetes.io/instance: filestore-app
  template:
    metadata:
      annotations: 
        checksum/configMaps: 36f71ca9a7d0278db7a132ff775ee4f3f74e662a1ece7418a2b0ccd94c2f9b58
      labels: 
        app.kubernetes.io/controller: filestore-api
        app.kubernetes.io/instance: filestore-app
        app.kubernetes.io/name: filestore-app
    spec: 
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      imagePullSecrets: 
        - name: cr-spydersoft-github
      containers: 
        - envFrom:
          - secretRef:
              name: filestore-secrets
          - configMapRef:
              name: filestore-app
          image: ghcr.io/spydersoft-consulting/filestore-api:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
          name: main
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 5m
---
# Source: filestore-api/templates/common.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: filestore-app
  labels:
    app.kubernetes.io/instance: filestore-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: filestore-app
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: filestore-api-1.0.0
  namespace: platform-production
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: envoy-gateway-system
  hostnames:
    - "filestore.mattgerega.com"
  rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: filestore-app
        namespace: platform-production
        port: 80
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
